baseURL = "https://www.patternfly.org/patternfly-elements/"
languageCode = "en-us"
title = "PatternFly Elements"
theme = "kube"
canonifyURLs = true

[Params]
  author = "PatternFly Elements" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "patternfly-elements-announce@redhat.com"
  features = [
    "Minimalism","Mobile-first Design",
    "Responsive Design",
    "Horizontal Rhythm",
    "Typography",
    "Google Analytics",
    "Disqus Commenting",
    "OpenGraph support",
    "Schema Structured Data",
    "Paginated Lists",
    "Reading Time",
    "Last Modified time",
    "Word Count",
    "Related Posts",
    "Block Templates",
    "Table of Contents",
    "SEO Site Verification"
  ]

[[menu.main]]
    name = "Getting Started"
    weight = 100
    url = "/:getting-started/"
[[menu.main]]
    name = "Develop"
    weight = 200
    url = "/:develop/"
[[menu.main]]
    name = "Theme"
    weight = 300
    url = "/:theme/"
    
[[menu.extra]]
    name = "Community"
    weight = 400
    url = "/:site-info/community"
[[menu.extra]]
    name = "Help"
    weight = 500
    url = "/:site-info/get-help"
    
    
[imaging]
  resampleFilter = "box"
  quality = 75
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"
