# This workflow will attempt to merge a pull request
# https://github.com/pascalgn/automerge-action
name: Auto-merge pull request if requirements met

on:
  workflow_run:
    workflows: ["Build & test"]
    types:
      - completed

jobs:
  try_to_merge:
    name: Try to merge the PR if allowed
    runs-on: ubuntu-latest
    steps:
      - name: Attempt merge
        if: github.event.workflow_run.conclusion == 'success
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!work in progress!,!on hold,!blocked,!needs: code updates,!needs: additional info,!needs: AT updates,!needs: changelog,!ready: branch testing,!ready: browser testing"
          MERGE_REMOVE_LABELS: "ready to merge"
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000
          UPDATE_METHOD: rebase
